server:
  port: 8081
management:
  endpoint:
    health:
      show-details: never
      cache:
        time-to-live: 10s
      probes:
        enabled: true
      access: read_only
  metrics:
    export:
      azure:
        enabled: true
        instrumentation-key: ""
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
        liveness: liveness
        readiness: readiness
      exposure:
        include: health, liveness, readiness
spring:
  application:
    name: operationsandexecution
  profiles:
    include: local
  messages:
    basename: messages
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=LoansDB
    username: sa
    password: Your_password123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/loansdb?authSource=admin
      database: loansdb
  main:
    log-startup-info: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: ALWAYS
azure:
  application-insights:
    connection-string: ""
  keyvault:
    secret:
      enabled: true
      uri: ""
      client-id: ""
      client-secret: ""
      tenant-id: ""
  storage:
    blob:
      enabled: true
      connection-string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:10000/devstoreaccount1;"
      container-name: "test"
rest:
  entrust:
    url: ""
logging:
  level:
    web: INFO
    root: INFO
    org.mongodb.driver: WARN
    com.azure: WARN
    io.netty: WARN
    org.springframework.data.repository.config: WARN
    org.springframework.boot: INFO
    org.springframework.data: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
    org.apache.catalina: INFO
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.springframework.cloud: WARN
    jakarta.persistence.spi: ERROR
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
